obj-y := ksu.o ksud.o allowlist.o apk_sign.o app_profile.o feature.o \
         file_wrapper.o kernel_umount.o pkg_observer.o seccomp_cache.o \
         selinux/ setuid_hook.o su_mount_ns.o sucompat.o \
         supercalls.o syscall_hook_manager.o throne_tracker.o \
         tiny_sulog.o util.o
